[package]
name = "mapdiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
serde_json = { version = "1.0.107" }
toml = "0.8.6"
octocrab = "0.31.2"
dmm-tools = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
dreammaker = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
ahash = "0.8.6"
path-absolutize = "3.1.1"
jsonwebtoken = "8.3.0"
eyre = "0.6.8"
simple-eyre = "0.3.1"
rayon = "1.8.0"
derive_builder = "0.12.0"
once_cell = "1.18.0"
image = "0.24.7"
diffbot_lib = { path = "../diffbot_lib" }
git2 = "0.18.1"
walkdir = "2.4.0"
delay_timer = "0.11.4"
hex = { version = "0.4.3", features = ["serde"] }
itertools = "0.11.0"
indexmap = { version = "2.0.2", features = ["rayon"] }
tracing-loki = "0.2.4"
flume = "0.11.0"

actix-web = "4.4.0"
actix-files = "0.6.2"

object_store = { version = "0.7.1", features = ["azure"] }
tokio = { version = "1.33.0", features = ["io-util", "rt"] }

mysql_async = "0.32.2"
time = "0.3.30"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.4"
