[package]
name = "icondiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
octocrab = "0.31.2"
dmm-tools = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
dreammaker = { git = "https://github.com/jupyterkat/SpacemanDMM/" }
once_cell = "1.18.0"
jsonwebtoken = "8.3.0"
reqwest = "0.11.22"
diffbot_lib = { path = "../diffbot_lib" }
eyre = "0.6.8"
simple-eyre = "0.3.1"
ndarray = "0.15.6"
rayon = "1.8.0"
toml = "0.8.6"
ahash = "0.8.6"
hashbrown = { version = "0.14.2", features = ["rayon"] }
hex = { version = "0.4.3", features = ["serde"] }
tracing-loki = "0.2.4"
flume = "0.11.0"

actix-web = "4.4.0"
actix-files = "0.6.2"

mysql_async = "0.32.2"
time = "0.3.30"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.4"

[dependencies.tracing]
version = "0.1.40"
features = ["attributes"]
